// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241221224426_initData")]
    partial class initData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("617feaa2-08b0-4433-9de0-88983525e371"),
                            Address = "942 Krystal Villages, West Rosemarychester, Comoros",
                            Country = "Cote d'Ivoire",
                            Name = "Ziemann, Predovic and West"
                        },
                        new
                        {
                            Id = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Address = "2616 Wuckert Extension, Raquelview, Indonesia",
                            Country = "France",
                            Name = "Gaylord Inc"
                        },
                        new
                        {
                            Id = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Address = "44089 Bogan Junctions, Jakaylaborough, Dominica",
                            Country = "Cyprus",
                            Name = "Dibbert LLC"
                        },
                        new
                        {
                            Id = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Address = "7772 Kamron Parkways, Breitenberghaven, Lesotho",
                            Country = "Liechtenstein",
                            Name = "Casper Inc"
                        },
                        new
                        {
                            Id = new Guid("7fdd53f7-34aa-4093-8ff6-ad2fb157cd22"),
                            Address = "522 Goldner Pike, East Laurianetown, Congo",
                            Country = "Ukraine",
                            Name = "Kihn - Haag"
                        },
                        new
                        {
                            Id = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Address = "4085 Little Rest, New Doriantown, Guadeloupe",
                            Country = "Guadeloupe",
                            Name = "Heaney, Ondricka and Pouros"
                        },
                        new
                        {
                            Id = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Address = "381 Goldner Circles, Port Alessandra, Cyprus",
                            Country = "Greece",
                            Name = "Konopelski and Sons"
                        },
                        new
                        {
                            Id = new Guid("dff2b225-e75a-48cf-8a06-19e89f25d140"),
                            Address = "677 Swift Shore, Sanfordshire, Slovakia (Slovak Republic)",
                            Country = "Gabon",
                            Name = "Mayer Group"
                        },
                        new
                        {
                            Id = new Guid("47680e25-cda2-4e85-919e-7d723d3dfcc2"),
                            Address = "2677 Osinski Meadow, West Adriel, Equatorial Guinea",
                            Country = "Saint Helena",
                            Name = "Halvorson, Jenkins and Gibson"
                        },
                        new
                        {
                            Id = new Guid("d5f6e332-c6e0-4c59-a148-6372b5599ae6"),
                            Address = "61437 Casandra Creek, Lake Magali, Saint Vincent and the Grenadines",
                            Country = "Trinidad and Tobago",
                            Name = "Ortiz and Sons"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58e021f0-9aab-453c-8ecd-6c319caa5d4f"),
                            Age = 40,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Marcus Mohr",
                            Position = "Product Solutions Director"
                        },
                        new
                        {
                            Id = new Guid("0d9df22a-4087-42c1-8df6-04e69c8a9e0f"),
                            Age = 55,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Miracle Hand",
                            Position = "District Optimization Coordinator"
                        },
                        new
                        {
                            Id = new Guid("40ae07b4-3b59-4812-8f67-3243a10b8f5e"),
                            Age = 59,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Torrance Kutch",
                            Position = "Future Response Planner"
                        },
                        new
                        {
                            Id = new Guid("8068c55a-095c-4351-bc37-d40eaec0e76f"),
                            Age = 50,
                            CompanyId = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Name = "Marley Funk",
                            Position = "Internal Directives Manager"
                        },
                        new
                        {
                            Id = new Guid("2b1fb753-e0e4-4ad4-b398-60833d50a38c"),
                            Age = 29,
                            CompanyId = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Name = "Bernita Kuhlman",
                            Position = "Central Quality Engineer"
                        },
                        new
                        {
                            Id = new Guid("256d64f6-6153-4968-8f8c-02fe5facb496"),
                            Age = 59,
                            CompanyId = new Guid("dff2b225-e75a-48cf-8a06-19e89f25d140"),
                            Name = "Lawson Medhurst",
                            Position = "Dynamic Mobility Administrator"
                        },
                        new
                        {
                            Id = new Guid("d0157999-7376-4583-9c74-4416262432a0"),
                            Age = 41,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Penelope Beatty",
                            Position = "Product Operations Assistant"
                        },
                        new
                        {
                            Id = new Guid("1e08e9c0-77b7-4b35-9c91-41d06276a080"),
                            Age = 50,
                            CompanyId = new Guid("617feaa2-08b0-4433-9de0-88983525e371"),
                            Name = "Brandt Gutmann",
                            Position = "Lead Solutions Architect"
                        },
                        new
                        {
                            Id = new Guid("648d1566-4f4e-467e-a672-afbb68dd9985"),
                            Age = 25,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Carolanne Farrell",
                            Position = "Central Integration Engineer"
                        },
                        new
                        {
                            Id = new Guid("1afb9570-9431-4104-8592-16cc6069f821"),
                            Age = 54,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Anabelle Monahan",
                            Position = "Lead Infrastructure Specialist"
                        },
                        new
                        {
                            Id = new Guid("58fd7707-df28-4e24-b867-1d7761679632"),
                            Age = 27,
                            CompanyId = new Guid("47680e25-cda2-4e85-919e-7d723d3dfcc2"),
                            Name = "Elvis Schroeder",
                            Position = "Corporate Division Facilitator"
                        },
                        new
                        {
                            Id = new Guid("20e3d58e-6e3d-4dbc-b28a-108b1f515fc6"),
                            Age = 29,
                            CompanyId = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Name = "Devonte Ankunding",
                            Position = "Legacy Metrics Consultant"
                        },
                        new
                        {
                            Id = new Guid("e5fdbeb1-0515-45b2-b005-56fd8c12c264"),
                            Age = 57,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Eldred Tremblay",
                            Position = "Regional Factors Coordinator"
                        },
                        new
                        {
                            Id = new Guid("96b71d80-f99f-49bb-9b72-d963e1e3fa13"),
                            Age = 57,
                            CompanyId = new Guid("d5f6e332-c6e0-4c59-a148-6372b5599ae6"),
                            Name = "Joannie Zemlak",
                            Position = "Future Intranet Facilitator"
                        },
                        new
                        {
                            Id = new Guid("b6e77138-a8a0-402c-842c-7c42f08fecae"),
                            Age = 31,
                            CompanyId = new Guid("dff2b225-e75a-48cf-8a06-19e89f25d140"),
                            Name = "Sheila Ferry",
                            Position = "Central Accountability Planner"
                        },
                        new
                        {
                            Id = new Guid("89c3c0f2-b20e-4d72-939e-d3cb4abcb5ff"),
                            Age = 38,
                            CompanyId = new Guid("d5f6e332-c6e0-4c59-a148-6372b5599ae6"),
                            Name = "Ladarius Daugherty",
                            Position = "International Operations Developer"
                        },
                        new
                        {
                            Id = new Guid("fad528ce-8b3e-445c-96b8-532c194f19fb"),
                            Age = 45,
                            CompanyId = new Guid("7fdd53f7-34aa-4093-8ff6-ad2fb157cd22"),
                            Name = "Isadore Satterfield",
                            Position = "Human Implementation Architect"
                        },
                        new
                        {
                            Id = new Guid("de59d77b-7bff-496f-baf0-db28d55e5b44"),
                            Age = 28,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Monty Dickens",
                            Position = "Regional Markets Associate"
                        },
                        new
                        {
                            Id = new Guid("7e4e69ac-8bb0-40ca-b7d3-c84db4e6f0ec"),
                            Age = 41,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Anibal Glover",
                            Position = "Principal Assurance Coordinator"
                        },
                        new
                        {
                            Id = new Guid("82ed97fa-7cfa-4f31-8de7-95d8049bd746"),
                            Age = 35,
                            CompanyId = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Name = "Travon O'Reilly",
                            Position = "International Markets Designer"
                        },
                        new
                        {
                            Id = new Guid("b21e7c78-29eb-42f2-b4ee-846c76da6fa1"),
                            Age = 28,
                            CompanyId = new Guid("7fdd53f7-34aa-4093-8ff6-ad2fb157cd22"),
                            Name = "Emerson Barrows",
                            Position = "Senior Security Agent"
                        },
                        new
                        {
                            Id = new Guid("2641473c-a1a8-415a-8228-a76e370b211b"),
                            Age = 55,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Alva Vandervort",
                            Position = "Legacy Optimization Designer"
                        },
                        new
                        {
                            Id = new Guid("56a547bd-962c-459e-92c5-7f21b9622d8e"),
                            Age = 41,
                            CompanyId = new Guid("617feaa2-08b0-4433-9de0-88983525e371"),
                            Name = "Keith Gibson",
                            Position = "Chief Intranet Engineer"
                        },
                        new
                        {
                            Id = new Guid("134f255a-e7b8-49f4-ab0c-b6d7c6cbe4ec"),
                            Age = 56,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Dusty Muller",
                            Position = "Dynamic Accountability Architect"
                        },
                        new
                        {
                            Id = new Guid("6551a838-3ed9-45c5-b372-33ce27d6ef40"),
                            Age = 24,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Denis Mertz",
                            Position = "Forward Web Liaison"
                        },
                        new
                        {
                            Id = new Guid("3b2a2647-bc9c-4eb3-a3f3-277edd4a1a22"),
                            Age = 47,
                            CompanyId = new Guid("47680e25-cda2-4e85-919e-7d723d3dfcc2"),
                            Name = "Porter Miller",
                            Position = "Dynamic Security Supervisor"
                        },
                        new
                        {
                            Id = new Guid("8923603d-1238-4c32-afcd-a0ca35382c2e"),
                            Age = 35,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Sarai Roberts",
                            Position = "District Paradigm Liaison"
                        },
                        new
                        {
                            Id = new Guid("2aa8952b-91c0-44f5-9e5d-8209ea3515db"),
                            Age = 31,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Cameron Rolfson",
                            Position = "Senior Implementation Facilitator"
                        },
                        new
                        {
                            Id = new Guid("d3b4f8d2-0ff2-466a-88b5-886b494f317a"),
                            Age = 24,
                            CompanyId = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Name = "Delaney Mohr",
                            Position = "Legacy Factors Executive"
                        },
                        new
                        {
                            Id = new Guid("d34cc149-a417-486f-b625-3b668a99cc6c"),
                            Age = 53,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Bobby Rohan",
                            Position = "Customer Solutions Administrator"
                        },
                        new
                        {
                            Id = new Guid("a799933d-beb9-476d-a545-1c7dd9c3603e"),
                            Age = 27,
                            CompanyId = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Name = "Lucinda Barton",
                            Position = "Dynamic Paradigm Analyst"
                        },
                        new
                        {
                            Id = new Guid("6b90df1e-13a7-4669-8675-fc47e96d5a18"),
                            Age = 25,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Priscilla Rempel",
                            Position = "Chief Quality Developer"
                        },
                        new
                        {
                            Id = new Guid("8c87fb67-1c1c-413a-a528-c12302348587"),
                            Age = 25,
                            CompanyId = new Guid("d5f6e332-c6e0-4c59-a148-6372b5599ae6"),
                            Name = "Simone Swift",
                            Position = "National Configuration Specialist"
                        },
                        new
                        {
                            Id = new Guid("db1d27e0-1bde-4d8e-be7d-8c6d8b3562fd"),
                            Age = 22,
                            CompanyId = new Guid("dff2b225-e75a-48cf-8a06-19e89f25d140"),
                            Name = "Uriel Turcotte",
                            Position = "Product Identity Analyst"
                        },
                        new
                        {
                            Id = new Guid("51c4a842-ab27-4992-ab72-5b001476b271"),
                            Age = 23,
                            CompanyId = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Name = "Zachariah Stokes",
                            Position = "International Data Architect"
                        },
                        new
                        {
                            Id = new Guid("485d7512-8f42-404c-98c5-cf444660160f"),
                            Age = 26,
                            CompanyId = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Name = "Jett Marvin",
                            Position = "Central Program Liaison"
                        },
                        new
                        {
                            Id = new Guid("d91466cd-9700-4b74-8ac1-6ef2ce42e38c"),
                            Age = 55,
                            CompanyId = new Guid("47680e25-cda2-4e85-919e-7d723d3dfcc2"),
                            Name = "Frieda Lakin",
                            Position = "Principal Quality Developer"
                        },
                        new
                        {
                            Id = new Guid("6c4d4728-065e-4127-953a-9c669ad9b183"),
                            Age = 56,
                            CompanyId = new Guid("159ebb19-771d-4cef-996d-a7a974c598b3"),
                            Name = "Alice Rohan",
                            Position = "Corporate Implementation Executive"
                        },
                        new
                        {
                            Id = new Guid("e91fa170-0e16-4aaa-91c7-4f31a4289710"),
                            Age = 29,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Wayne Wehner",
                            Position = "Customer Security Director"
                        },
                        new
                        {
                            Id = new Guid("4dc1aa2c-6f0f-47d1-ab90-c8f48df02fb5"),
                            Age = 56,
                            CompanyId = new Guid("47680e25-cda2-4e85-919e-7d723d3dfcc2"),
                            Name = "Ana Lang",
                            Position = "Product Program Supervisor"
                        },
                        new
                        {
                            Id = new Guid("fdd73d81-dec4-4db8-ba29-1f6f3a83bb11"),
                            Age = 28,
                            CompanyId = new Guid("4904ae42-f898-4bac-b795-645fd90519cc"),
                            Name = "Jon Roob",
                            Position = "Forward Security Administrator"
                        },
                        new
                        {
                            Id = new Guid("d2702671-cc66-42f9-910d-c2497187d645"),
                            Age = 35,
                            CompanyId = new Guid("617feaa2-08b0-4433-9de0-88983525e371"),
                            Name = "Raymond Kris",
                            Position = "Senior Interactions Officer"
                        },
                        new
                        {
                            Id = new Guid("7b49411c-18d7-476e-b178-346582c7e133"),
                            Age = 60,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Harmon Oberbrunner",
                            Position = "Central Operations Supervisor"
                        },
                        new
                        {
                            Id = new Guid("33c870dc-41eb-4d15-8c25-97a572b3df32"),
                            Age = 59,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Gillian Ruecker",
                            Position = "Chief Creative Coordinator"
                        },
                        new
                        {
                            Id = new Guid("e366b5b8-2ec3-471d-a5c2-8020849b1c49"),
                            Age = 32,
                            CompanyId = new Guid("617feaa2-08b0-4433-9de0-88983525e371"),
                            Name = "Karlie Schiller",
                            Position = "Central Functionality Administrator"
                        },
                        new
                        {
                            Id = new Guid("e48749df-e54c-47d0-98c0-2fcb7c6dd0e3"),
                            Age = 32,
                            CompanyId = new Guid("3a102b47-5906-4d49-a4c3-19e18d7e60fb"),
                            Name = "Coy Rogahn",
                            Position = "Customer Operations Specialist"
                        },
                        new
                        {
                            Id = new Guid("8fabcfe5-abfc-4760-84f4-73faea003d1e"),
                            Age = 55,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Roberta Corwin",
                            Position = "Global Division Engineer"
                        },
                        new
                        {
                            Id = new Guid("bb90070a-d48d-4ec5-a5b4-b0418b63299c"),
                            Age = 22,
                            CompanyId = new Guid("b1d28805-064b-4ca1-9bb4-5adaae8f8867"),
                            Name = "Bryana Shields",
                            Position = "Lead Creative Engineer"
                        },
                        new
                        {
                            Id = new Guid("6ebba1c1-5d8b-4a5c-9a7f-780eaeaaf37b"),
                            Age = 47,
                            CompanyId = new Guid("66cbbac2-ff53-40f4-88e8-d8c182223b7e"),
                            Name = "Elouise Sanford",
                            Position = "District Configuration Planner"
                        },
                        new
                        {
                            Id = new Guid("326c0964-8e59-45a4-a7a1-24e5c6c13e46"),
                            Age = 43,
                            CompanyId = new Guid("d5f6e332-c6e0-4c59-a148-6372b5599ae6"),
                            Name = "Craig Rodriguez",
                            Position = "Corporate Quality Strategist"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
